title: My Static Page
author: GoroCollins
email: gorocollins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by Collins.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
